In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [9]:
arr - 3

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [10]:
arr / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        , 2.33333333, 2.66666667, 3.        , 3.33333333])

In [11]:
1/0

ZeroDivisionError: division by zero

In [12]:
arr / 0

C:\Users\Davis\AppData\Local\Temp\ipykernel_11684\3942562399.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [13]:
arr = np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr / 0

C:\Users\Davis\AppData\Local\Temp\ipykernel_11684\3942562399.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0
C:\Users\Davis\AppData\Local\Temp\ipykernel_11684\3942562399.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [16]:
arr / arr

C:\Users\Davis\AppData\Local\Temp\ipykernel_11684\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [17]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [18]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [19]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [20]:
np.max(arr)

10

In [21]:
np.min(arr)

0

In [22]:
arr.max()

10

In [23]:
arr.min()

0