In [1]:
import numpy as np

In [10]:
arr = np.random.randint(1, 21, 10)
new_arr = arr[1:6]
print(arr, new_arr)


[13 18  7 11 16 18  7 19 17 18] [18  7 11 16 18]


In [9]:
arr = np.random.randint(0, 21, 10)
new_arr = arr[2:]
print(arr, new_arr)

[13  9 20  7 13 19  7 16  2  1] [20  7 13 19  7 16  2  1]
[20  7 13 19  7 16  2  1]


In [8]:
arr = np.random.randint(3, 12, 12).reshape(4, 3)
new_arr = arr[1:3, :2]
print(arr, new_arr)

[[ 8  3  7]
 [11 11  9]
 [ 3  3 10]
 [10  9  4]] [[11 11]
 [ 3  3]]


In [7]:
arr = np.random.randint(0, 10, 24).reshape(4, 6)
new_arr = arr[arr > 3]
print(arr, new_arr)

[[4 5 7 6 9 9]
 [0 6 5 4 3 9]
 [3 9 3 3 2 2]
 [7 1 2 5 0 4]] [4 5 7 6 9 9 6 5 4 9 9 7 5 4]
