In [1]:
import numpy as np

In [3]:
arr1 = np.random.randint(1, 21, 10)
arr2 = np.arange(2, 12)
print(arr1, arr2)
print(arr1 + arr2)

[ 9 18 12  8  9 12 20  2  5  3] [ 2  3  4  5  6  7  8  9 10 11]
[11 21 16 13 15 19 28 11 15 14]


In [4]:
arr1 = np.random.randint(0, 10, 7)
arr2 = arr1 * 3
print(arr1, arr2)

[2 8 8 0 8 8 2] [ 6 24 24  0 24 24  6]


In [5]:
arr = np.sqrt(np.arange(7, 27))
print(arr)

[2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152 4.89897949
 5.         5.09901951]
