In [11]:
import numpy as np

Создайте массив из списка, , состоящего из чисел от 0 до 9, при помощи функции array() из модуля numpy

In [12]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Создайте массив , состоящий из нечётных чисел от 1 до 19, при помощи функции arange() из модуля numpy

In [5]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Создайте массив , состоящий из двадцати нулей

In [13]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

Создайте двумерный массив , состоящий из двадцати единиц, в котором 5 строк и 4 столбца

In [14]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Создайте массив , состоящий из пяти равномерно распределённых чисел от 3 до 7

In [15]:
np.linspace(3,5,7)

array([3.        , 3.33333333, 3.66666667, 4.        , 4.33333333,
       4.66666667, 5.        ])

Создайте двумерный массив , состоящий из 9 равномерно распределённых чисел от 3 до 7

In [21]:
np.linspace(3,7,9)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ])

Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 1 до 100, присвойте его максимальное значение переменной max_number и выведите значение этой переменной при помощи функции print()

In [31]:
rand_arr = np.random.randint(1, 100, 10)
rand_arr

array([42, 61, 98, 93, 50, 67, 46, 26, 72, 34])

In [32]:
max_number = rand_arr.max()

In [33]:
print(max_number)

98
