In [13]:
import numpy as np

In [14]:
int_arr = np.random.randint(0,10,10)

In [15]:
int_arr

array([2, 1, 1, 6, 2, 4, 9, 9, 6, 5])

In [16]:
int_arr[0]

2

In [17]:
int_arr[9]

5

In [18]:
int_arr[1:3]

array([1, 1])

In [19]:
int_arr[1:7]

array([1, 1, 6, 2, 4, 9])

In [20]:
int_arr[0:4]

array([2, 1, 1, 6])

In [21]:
int_arr[:4]

array([2, 1, 1, 6])

In [22]:
int_arr[4:]

array([2, 4, 9, 9, 6, 5])

In [23]:
int_arr[4:] = 10

In [24]:
int_arr

array([ 2,  1,  1,  6, 10, 10, 10, 10, 10, 10])

In [25]:
arr = np.arange(0,10)

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
new_arr = arr[:4]

In [28]:
new_arr

array([0, 1, 2, 3])

In [29]:
new_arr[2:] = 7

In [30]:
new_arr

array([0, 1, 7, 7])

In [31]:
arr

array([0, 1, 7, 7, 4, 5, 6, 7, 8, 9])

In [32]:
arr = np.arange(0,10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
new_arr = arr.copy()

In [35]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
new_arr[:] = 0

In [37]:
new_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [40]:
bool_arr = arr > 6

In [41]:
bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [42]:
arr[bool_arr]

array([7, 8, 9])

In [43]:
bool_arr = arr > 0

In [44]:
arr[bool_arr]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[arr > 0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])