In [8]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

Docstring Shortcut Shift + Tab

In [3]:
odd_number_list = [1,3,5,7,9]

In [4]:
np.array(odd_number_list)

array([1, 3, 5, 7, 9])

In [6]:
two_dim_list = [[1,1,1],[2,2,2],[3,3,3]]
np.array(two_dim_list)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [19]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.60934541, 0.92560104, 0.5887828 , 0.29647109, 0.37440636])

In [23]:
np.random.rand(3,4)

array([[0.96467071, 0.43025856, 0.84571854, 0.83407378],
       [0.12476843, 0.41260032, 0.45877287, 0.74567064],
       [0.69512054, 0.81964361, 0.74307777, 0.38280816]])

In [24]:
np.random.randn(3,4)

array([[ 0.22968925, -0.03392295,  0.20049133, -0.41701486],
       [-1.05926423,  0.06207837,  0.84002661, -1.15544405],
       [ 0.71583297,  3.39422299, -0.85784641,  0.04962143]])

In [25]:
np.random.randint(0, 50, 2)

array([47, 40])

In [26]:
np.random.randint(0, 50, 20)

array([ 1,  1, 35, 44,  0, 30, 17,  2, 40,  1, 22, 23, 49, 15,  0, 23,  7,
       43, 25, 38])

In [27]:
rand_arr = np.random.randint(0, 50, 20)

In [28]:
rand_arr

array([ 7, 40, 33, 36, 43, 28, 44, 36, 30, 10, 27, 25, 46, 26, 40, 27, 23,
       29, 38,  1])

In [29]:
second_arr = np.arange(20)

In [30]:
second_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
rand_arr.reshape(4,5)

array([[ 7, 40, 33, 36, 43],
       [28, 44, 36, 30, 10],
       [27, 25, 46, 26, 40],
       [27, 23, 29, 38,  1]])

In [32]:
second_arr.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [33]:
second_arr.max()

19

In [34]:
second_arr.min()

0

In [35]:
second_arr.argmax()

19

In [36]:
rand_arr.max()

46

In [37]:
rand_arr.argmax()

12

In [38]:
rand_arr.min()

1

In [39]:
rand_arr.argmin()

19

In [40]:
second_arr.shape

(20,)

In [41]:
reshaped_arr = second_arr.reshape(2,10)

In [42]:
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [43]:
reshaped_arr.shape

(2, 10)

In [44]:
reshaped_arr.dtype

dtype('int32')